name = "weather-api-dev"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./static"
binding = "ASSETS"

[[kv_namespaces]]
binding = "LOGS_KV"
id = "502d7ca869de42afbce1f6e2a7099f63"

[vars]
APP_ENV = "development"

[env.staging]
name = "weather-api-staging"

[env.staging.vars]
APP_ENV = "staging"

[[env.staging.kv_namespaces]]
binding = "LOGS_KV"
id = "502d7ca869de42afbce1f6e2a7099f63"

[env.production]
name = "weather-api-prod"

[env.production.vars]
APP_ENV = "production"

[[env.production.kv_namespaces]]
binding = "LOGS_KV"
id = "502d7ca869de42afbce1f6e2a7099f63"